import type { NextPage } from "next";
import Head from "next/head";
import SearchBar from "../components/SearchBar";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen flex justify-center mt-28">
        <SearchBar />
      </main>
    </div>
  );
};

export default Home;
